name: Beta

on:
  push:
    branches:
      - shilan-workflow-trigger-test2

env:
  XCODE_CONFIG: Beta
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
  APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
  APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
  MATCH_GIT_BASIC_AUTHORIZATION_BASE64: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION_BASE64 }}
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-deploy-beta:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4